/**
 * Each entity config drives a generic CRUD page:
 *  - key: route slug
 *  - title: page heading
 *  - endpoint: backend REST path (mounted under /api)
 *  - pk: primary key field name
 *  - pkEditable: whether the pk can be typed by the user on create (true for
 *    business keys like CustomerID, false for auto-increment ids)
 *  - fields: form + table field definitions
 */

const YES_NO = [
  { value: 1, label: 'Active (1)' },
  { value: 0, label: 'Inactive (0)' },
];

export const entities = {
  userGroups: {
    key: 'user-groups',
    title: 'Web Group Name Master',
    subtitle: 'Create user groups under a Group Type (Internal User / Field User) for the web application.',
    endpoint: '/user-groups',
    pk: 'GroupNameID',
    pkEditable: true,
    fields: [
      { name: 'GroupNameID', label: 'Group Name ID', type: 'text', required: true },
      { name: 'UserGroupType', label: 'User Group Type', type: 'select', options: ['Internal User', 'Field User'], required: true },
      { name: 'UserGroupName', label: 'User Group Name', type: 'text', placeholder: 'R&D / Admin / Customer' },
      { name: 'GroupNameDescription', label: 'Description', type: 'textarea' },
    ],
  },

  /*customers: {
    key: 'customers',
    title: 'Web Customer Master',
    subtitle: 'Visible only to the REILADMIN user.',
    endpoint: '/customers',
    pk: 'CustomerID',
    pkEditable: true,
    fields: [
      { name: 'CustomerID', label: 'Customer ID', type: 'text', required: true },
      { name: 'CustomerName', label: 'Customer Name', type: 'text', required: true },
      { name: 'CustomerDescription', label: 'Customer Description', type: 'textarea' },
    ],
  },*/

  customers: {
  key: 'customers',
  title: 'Web Customer Master',
  subtitle: 'Visible only to the REILADMIN user.',
  endpoint: '/customers',
  pk: 'CustomerID',
  pkEditable: true,
  fields: [
    { name: 'CustomerID', label: 'Customer ID', type: 'text', required: true },
    { name: 'CustomerName', label: 'Customer Name', type: 'text', required: true },
    {
      name: 'GroupNameID',
      label: 'Group Name',
      type: 'select',
      optionsEndpoint: '/user-groups',
      optionsValue: 'GroupNameID',
      optionsLabel: 'UserGroupName',
    },
    { name: 'CustomerDescription', label: 'Customer Description', type: 'textarea' },
  ],
},

 /* locations: {
    key: 'locations',
    title: 'Web Location Master',
    subtitle: 'Visible to (CustomerName+ADMIN), REILADMIN, and REILMarketingADMIN users.',
    endpoint: '/locations',
    pk: 'LocationID',
    pkEditable: true,
    fields: [
      { name: 'LocationID', label: 'Location ID', type: 'text', required: true },
      { name: 'CustomerName', label: 'Customer Name', type: 'text', required: true },
      { name: 'LocationName', label: 'Location Name', type: 'text', required: true },
      { name: 'LocationDescription', label: 'Location Description', type: 'textarea' },
    ],
  },*/

  locations: {
  key: 'locations',
  title: 'Web Location Master',
  subtitle: 'Visible to (CustomerName+ADMIN), REILADMIN, and REILMarketingADMIN users.',
  endpoint: '/locations',
  pk: 'LocationID',
  pkEditable: true,
  fields: [
    { name: 'LocationID', label: 'Location ID', type: 'text', required: true },
    {
      name: 'GroupNameID',
      label: 'Group Name',
      type: 'select',
      optionsEndpoint: '/user-groups',
      optionsValue: 'GroupNameID',
      optionsLabel: 'UserGroupName',
      uiOnly: true,
    },
    {
      name: 'CustomerID',
      label: 'Customer',
      type: 'select',
      optionsEndpoint: '/customers',
      optionsValue: 'CustomerID',
      optionsLabel: 'CustomerName',
      dependsOn: 'GroupNameID',
      filterKey: 'GroupNameID',
      required: true,
    },
    { name: 'LocationName', label: 'Location Name', type: 'text', required: true },
    { name: 'LocationDescription', label: 'Location Description', type: 'textarea' },
  ],
},

  /*maxUserCount: {
    key: 'max-user-count',
    title: 'Maximum Field User Count',
    subtitle: 'Per-customer user limits. Note: no max user limit applies where Group Type = Internal.',
    endpoint: '/max-user-count',
    pk: 'CustomerID',
    pkEditable: true,
    fields: [
      { name: 'CustomerID', label: 'Customer ID', type: 'text', required: true },
      { name: 'MaxWebLocationUsers', label: 'Max Web Location Users', type: 'number' },
      { name: 'MaxWebCustomerUsers', label: 'Max Web Customer Users', type: 'number' },
      { name: 'MaxWebMobileAppUsers', label: 'Max Web Mobile App Users', type: 'number' },
      { name: 'MaxMobileUsers', label: 'Max Mobile Users', type: 'number' },
    ],
  },*/

  maxUserCount: {
  key: 'max-user-count',
  title: 'Maximum Field User Count',
  subtitle: 'Per-customer user limits. Note: no max user limit applies where Group Type = Internal.',
  endpoint: '/max-user-count',
  pk: 'CustomerID',
  pkEditable: true,
  fields: [
    {
      name: 'GroupNameID',
      label: 'Group Name',
      type: 'select',
      optionsEndpoint: '/user-groups',
      optionsValue: 'GroupNameID',
      optionsLabel: 'UserGroupName',
      uiOnly: true,
    },
    {
      name: 'CustomerID',
      label: 'Customer',
      type: 'select',
      optionsEndpoint: '/customers',
      optionsValue: 'CustomerID',
      optionsLabel: 'CustomerName',
      dependsOn: 'GroupNameID',
      filterKey: 'GroupNameID',
      required: true,
    },
    { name: 'MaxWebLocationUsers', label: 'Max Web Location Users', type: 'number' },
    { name: 'MaxWebCustomerUsers', label: 'Max Web Customer Users', type: 'number' },
    { name: 'MaxWebMobileAppUsers', label: 'Max Web Mobile App Users', type: 'number' },
    { name: 'MaxMobileUsers', label: 'Max Mobile Users', type: 'number' },
  ],
},

  /*webUsers: {
    key: 'web-users',
    title: 'Web User Master',
    subtitle: 'New user creation under a specific User Group (Customer / Location).',
    endpoint: '/web-users',
    pk: 'UserID',
    pkEditable: true,
    fields: [
      { name: 'UserID', label: 'User ID', type: 'text', required: true },
      { name: 'CustomerID', label: 'Customer ID', type: 'text' },
      { name: 'LocationID', label: 'Location ID', type: 'text' },
      { name: 'UserLevel', label: 'User Level', type: 'select', options: ['ADMIN', 'OFFICER', 'TECHNICIAN', 'Customer', 'Location', 'MobileApp'] },
      { name: 'UserGroupType', label: 'User Group Type', type: 'select', options: ['Internal User', 'Field User'] },
      { name: 'UserGroupName', label: 'User Group Name', type: 'text', placeholder: 'R&D / Admin / Customer' },
      { name: 'NameOfUser', label: 'Name of User', type: 'text', required: true },
      { name: 'LoginID', label: 'Login ID', type: 'text', required: true },
      { name: 'Password', label: 'Password', type: 'password', required: true },
      { name: 'UserActivationFlag', label: 'Activation Flag', type: 'select', options: YES_NO },
      { name: 'Designation', label: 'Designation', type: 'text' },
      { name: 'EmailID', label: 'Email ID', type: 'text' },
      { name: 'MobileNo', label: 'Mobile No. (10 digits)', type: 'text', maxLength: 10 },
      { name: 'CustomerName', label: 'Customer Name', type: 'text' },
      { name: 'LocationName', label: 'Location Name', type: 'text' },
    ],
  },*/

  webUsers: {
  key: 'web-users',
  title: 'Web User Master',
  subtitle: 'New user creation under a specific User Group (Customer / Location).',
  endpoint: '/web-users',
  pk: 'UserID',
  pkEditable: true,
  fields: [
    { name: 'UserID', label: 'User ID', type: 'text', required: true },
    {
      name: 'GroupNameID',
      label: 'Group Name',
      type: 'select',
      optionsEndpoint: '/user-groups',
      optionsValue: 'GroupNameID',
      optionsLabel: 'UserGroupName',
      uiOnly: true,
      autofill: { UserGroupType: 'UserGroupType', UserGroupName: 'UserGroupName' },
    },
    {
      name: 'CustomerID',
      label: 'Customer',
      type: 'select',
      optionsEndpoint: '/customers',
      optionsValue: 'CustomerID',
      optionsLabel: 'CustomerName',
      dependsOn: 'GroupNameID',
      filterKey: 'GroupNameID',
      autofill: { CustomerName: 'CustomerName' },
    },
    {
      name: 'LocationID',
      label: 'Location',
      type: 'select',
      optionsEndpoint: '/locations',
      optionsValue: 'LocationID',
      optionsLabel: 'LocationName',
      dependsOn: 'CustomerID',
      filterKey: 'CustomerID',
      autofill: { LocationName: 'LocationName' },
    },
    { name: 'UserLevel', label: 'User Level', type: 'select', options: ['ADMIN', 'OFFICER', 'TECHNICIAN', 'Customer', 'Location', 'MobileApp'] },
    { name: 'UserGroupType', label: 'User Group Type', type: 'text', hiddenInForm: true },
    { name: 'UserGroupName', label: 'User Group Name', type: 'text', hiddenInForm: true },
    { name: 'NameOfUser', label: 'Name of User', type: 'text', required: true },
    { name: 'LoginID', label: 'Login ID', type: 'text', required: true },
    { name: 'Password', label: 'Password', type: 'password', required: true },
    { name: 'UserActivationFlag', label: 'Activation Flag', type: 'select', options: YES_NO },
    { name: 'Designation', label: 'Designation', type: 'text' },
    { name: 'EmailID', label: 'Email ID', type: 'text' },
    { name: 'MobileNo', label: 'Mobile No. (10 digits)', type: 'text', maxLength: 10 },
    { name: 'CustomerName', label: 'Customer Name', type: 'text', hiddenInForm: true },
    { name: 'LocationName', label: 'Location Name', type: 'text', hiddenInForm: true },
  ],
},

  /*mobileUsers: {
    key: 'mobile-users',
    title: 'Mobile User Master',
    subtitle: 'Mobile app user creation under Customer / Location.',
    endpoint: '/mobile-users',
    pk: 'MobileAppUserID',
    pkEditable: true,
    fields: [
      { name: 'MobileAppUserID', label: 'Mobile App User ID', type: 'text', required: true },
      { name: 'CustomerID', label: 'Customer ID', type: 'text' },
      { name: 'LocationID', label: 'Location ID', type: 'text' },
      { name: 'UserGroupType', label: 'User Group Type', type: 'select', options: ['Internal User', 'Field User'] },
      { name: 'UserGroupName', label: 'User Group Name', type: 'text' },
      { name: 'NameOfUser', label: 'Name of User', type: 'text' },
      { name: 'LoginID', label: 'Login ID', type: 'text' },
      { name: 'Password', label: 'Password', type: 'password' },
      { name: 'UserActivationFlag', label: 'Activation Flag', type: 'select', options: YES_NO },
      { name: 'Designation', label: 'Designation', type: 'text' },
      { name: 'EmailID', label: 'Email ID', type: 'text' },
      { name: 'MobileNo', label: 'Mobile No. (10 digits)', type: 'text', maxLength: 10 },
      { name: 'CustomerName', label: 'Customer Name', type: 'text' },
      { name: 'LocationName', label: 'Location Name', type: 'text' },
    ],
  },*/

  mobileUsers: {
  key: 'mobile-users',
  title: 'Mobile User Master',
  subtitle: 'Mobile app user creation under Customer / Location.',
  endpoint: '/mobile-users',
  pk: 'MobileAppUserID',
  pkEditable: true,
  fields: [
    { name: 'MobileAppUserID', label: 'Mobile App User ID', type: 'text', required: true },
    {
      name: 'GroupNameID',
      label: 'Group Name',
      type: 'select',
      optionsEndpoint: '/user-groups',
      optionsValue: 'GroupNameID',
      optionsLabel: 'UserGroupName',
      uiOnly: true,
      autofill: { UserGroupType: 'UserGroupType', UserGroupName: 'UserGroupName' },
    },
    {
      name: 'CustomerID',
      label: 'Customer',
      type: 'select',
      optionsEndpoint: '/customers',
      optionsValue: 'CustomerID',
      optionsLabel: 'CustomerName',
      dependsOn: 'GroupNameID',
      filterKey: 'GroupNameID',
      autofill: { CustomerName: 'CustomerName' },
    },
    {
      name: 'LocationID',
      label: 'Location',
      type: 'select',
      optionsEndpoint: '/locations',
      optionsValue: 'LocationID',
      optionsLabel: 'LocationName',
      dependsOn: 'CustomerID',
      filterKey: 'CustomerID',
      autofill: { LocationName: 'LocationName' },
    },
    { name: 'UserGroupType', label: 'User Group Type', type: 'text', hiddenInForm: true },
    { name: 'UserGroupName', label: 'User Group Name', type: 'text', hiddenInForm: true },
    { name: 'NameOfUser', label: 'Name of User', type: 'text' },
    { name: 'LoginID', label: 'Login ID', type: 'text' },
    { name: 'Password', label: 'Password', type: 'password' },
    { name: 'UserActivationFlag', label: 'Activation Flag', type: 'select', options: YES_NO },
    { name: 'Designation', label: 'Designation', type: 'text' },
    //{ name: 'EmailID', label: 'Email ID', type: 'text' },
    { name: 'EmailID', label: 'Email ID', type: 'text', required: true, pattern: 'email' },
    { name: 'MobileNo', label: 'Mobile No. (10 digits)', type: 'text', required: true, pattern: 'mobile10', maxLength: 10 },
    //{ name: 'MobileNo', label: 'Mobile No. (10 digits)', type: 'text', maxLength: 10 },
    { name: 'CustomerName', label: 'Customer Name', type: 'text', hiddenInForm: true },
    { name: 'LocationName', label: 'Location Name', type: 'text', hiddenInForm: true },
  ],
},

  ppcLotComponent: {
    key: 'ppc-lot-component',
    title: 'PPC Lot Details of Component (PCB)',
    subtitle: 'Algorithm 1 — Part No. and total component count auto-fill from PPC Master.',
    endpoint: '/ppc-lot-component',
    pk: 'id',
    pkEditable: false,
    fields: [
      { name: 'ComponentName', label: 'Component Name', type: 'text', default: 'PCB' },
      { name: 'PPCNo', label: 'PPC No.', type: 'text', required: true },
      { name: 'PartNo', label: 'Part No.', type: 'text' },
      { name: 'TotalComponentsAsPerPPC', label: 'Total Components as per PPC', type: 'number' },
    ],
  },

  /*componentLotMaster: {
    key: 'component-lot-master',
    title: 'Component Lot Master',
    subtitle: 'Algorithm 2 — generate/print new QR codes for lots and map QR to a Lot Serial Number.',
    endpoint: '/component-lot-master',
    pk: 'id',
    pkEditable: false,
    fields: [
      { name: 'ComponentName', label: 'Component Name', type: 'text', default: 'PCB' },
      { name: 'PPCNo', label: 'PPC No.', type: 'text' },
      { name: 'ComponentLotSerialNo', label: 'Component Lot Serial No.', type: 'text' },
      { name: 'ComponentLotQRCodeNo', label: 'Component Lot QR Code No.', type: 'text' },
      { name: 'ComponentLotQRCodeLabel', label: 'Component Lot QR Code Label', type: 'text' },
      { name: 'ComponentLotQRCodeImage', label: 'Component Lot QR Code Image (path/URL)', type: 'text' },
      { name: 'ComponentCurrentLotMaxSize', label: 'Current Lot Max Size', type: 'number' },
      { name: 'NoOfNewQRCodeRequired', label: 'No. of New QR Codes Required', type: 'number' },
    ],
  },*/

 componentLotMaster: {
  key: 'component-lot-master',
  title: 'Component Lot Master',
  subtitle: 'Algorithm 2 — map an available (unallotted) QR code to a Lot.',
  endpoint: '/component-lot-master',
  pk: 'id',
  pkEditable: false,
  fields: [
    { name: 'ComponentName', label: 'Component Name', type: 'text', default: 'PCB' },
    {
      name: 'PPCNo',
      label: 'PPC No.',
      type: 'select',
      optionsEndpoint: '/ppc-lot-component',
      optionsValue: 'PPCNo',
      optionsLabel: 'PPCNo',
    },
    { name: 'ComponentLotSerialNo', label: 'Component Lot Serial No.', type: 'text' },
    {
      name: 'ComponentLotQRCodeNo',
      label: 'Component Lot QR Code No.',
      type: 'select',
      optionsEndpoint: '/process/ppc-lot-qr/available',
      optionsValue: 'LotQRCodeNo',
      optionsLabel: 'LotQRCodeNo',
      linkGroup: 'qrLink',
      resolveColumn: 'LotQRCodeNo',
    },
    {
      name: 'ComponentLotQRCodeLabel',
      label: 'Component Lot QR Code Label',
      type: 'select',
      optionsEndpoint: '/process/ppc-lot-qr/available',
      optionsValue: 'LotQRCodeLabel',
      optionsLabel: 'LotQRCodeLabel',
      linkGroup: 'qrLink',
      resolveColumn: 'LotQRCodeLabel',
    },
    {
      name: 'ComponentLotQRCodeImage',
      label: 'Component Lot QR Code Image (path/URL)',
      type: 'select',
      optionsEndpoint: '/process/ppc-lot-qr/available',
      optionsValue: 'LotQRCodeLabel',
      optionsLabel: 'LotQRCodeLabel',
      linkGroup: 'qrLink',
      resolveColumn: 'LotQRCodeImage',
    },
    { name: 'ComponentCurrentLotMaxSize', label: 'Current Lot Max Size', type: 'number' },
  ],
},
  componentQrMaster: {
    key: 'component-qr-master',
    title: 'Component QR Code Master',
    subtitle: 'Algorithm 3 — generate/print QR codes for components and map to Component Serial No.',
    endpoint: '/component-qr-master',
    pk: 'id',
    pkEditable: false,
    fields: [
      { name: 'ComponentName', label: 'Component Name', type: 'text', default: 'PCB' },
      { name: 'PPCNo', label: 'PPC No.', type: 'text' },
      { name: 'ComponentLotId', label: 'Component Lot ID', type: 'text' },
      { name: 'ComponentSerialNo', label: 'Component Serial No.', type: 'number' },
      { name: 'ComponentQRCodeNo', label: 'Component QR Code No.', type: 'text' },
      { name: 'ComponentQRCodeLabel', label: 'Component QR Code Label', type: 'text' },
      { name: 'ComponentQRCodeImage', label: 'Component QR Code Image (path/URL)', type: 'text' },
      { name: 'NoOfNewQRCodeRequired', label: 'No. of New QR Codes Required', type: 'number' },
      { name: 'ComponentDepartmentFlag', label: 'Department Flag', type: 'select', options: [{ value: 1, label: '1 - Production' }, { value: 2, label: '2 - QA' }, { value: 3, label: '3 - FGS' }] },
      { name: 'ComponentCurrentLotSizeFilled', label: 'Current Lot Size Filled', type: 'number' },
      { name: 'TotalComponentsProducedTillDate', label: 'Total Components Produced Till Date', type: 'number' },
      { name: 'TotalComponentsProducedWithQRTillDate', label: 'Total Components Produced (QR generated) Till Date', type: 'number' },
      { name: 'NoComponentsNeedNewQRCode', label: 'Components Needing New QR Code', type: 'number' },
      { name: 'ComponentDispatchFlag', label: 'Dispatch Flag (0/1)', type: 'select', options: YES_NO },
    ],
  },

  componentFaultMaster: {
    key: 'component-fault-master',
    title: 'Component Fault Master (PCB)',
    subtitle: 'Algorithm 4 — Major / Minor fault categories for PCB.',
    endpoint: '/component-fault-master',
    pk: 'id',
    pkEditable: false,
    fields: [
      { name: 'ComponentName', label: 'Component Name', type: 'text', default: 'PCB' },
      { name: 'FaultMajorCategoryID', label: 'Fault Major Category ID', type: 'text' },
      { name: 'FaultMajorCategoryName', label: 'Fault Major Category Name', type: 'text', required: true },
      { name: 'FaultMinorCategoryID', label: 'Fault Minor Category ID', type: 'text' },
      { name: 'FaultMinorCategoryName', label: 'Fault Minor Category Name', type: 'text', required: true },
    ],
  },

  communicationLogComponent: {
    key: 'communication-log-component',
    title: 'Communication Log — Component (PCB)',
    subtitle: 'Department hand-off audit trail for PCB components.',
    endpoint: '/communication-log-component',
    pk: 'id',
    pkEditable: false,
    readOnly: true,
    fields: [
      { name: 'PPCNo', label: 'PPC No.', type: 'text' },
      { name: 'ComponentSerialNo', label: 'Component Serial No.', type: 'text' },
      { name: 'LotNo', label: 'Lot No.', type: 'text' },
      { name: 'FromDepartmentName', label: 'From Department', type: 'text' },
      { name: 'ToDepartmentName', label: 'To Department', type: 'text' },
      { name: 'UserIDFromDept', label: 'User ID (From Dept)', type: 'text' },
      { name: 'OperationNameCompletedByFromDept', label: 'Operation Completed', type: 'text' },
      { name: 'DateTimeOfTransfer', label: 'Date/Time of Transfer', type: 'text' },
    ],
  },

  ppcMilkosens: {
    key: 'ppc-milkosens',
    title: 'PPC Details for Milkosens',
    subtitle: 'Algorithm 1 — visible to PPC Department, Admin, or R&D only.',
    endpoint: '/ppc-milkosens',
    pk: 'id',
    pkEditable: false,
    fields: [
      { name: 'PPCNo', label: 'PPC No.', type: 'text', required: true },
      { name: 'ProductName', label: 'Product Name', type: 'text', default: 'Milkosens' },
      { name: 'PartNo', label: 'Part No.', type: 'text' },
      { name: 'TotalProductsAsPerPPC', label: 'Total Products as per PPC', type: 'number' },
      { name: 'MaxLotSize', label: 'Max Lot Size', type: 'number' },
    ],
  },

  milkosensLotMaster: {
    key: 'milkosens-lot-master',
    title: 'Milkosens Lot Master',
    subtitle: 'Algorithm 2 — visible to Production Department, Admin, or R&D only.',
    endpoint: '/milkosens-lot-master',
    pk: 'id',
    pkEditable: false,
    fields: [
      { name: 'ProductName', label: 'Product Name', type: 'text', default: 'Milkosens' },
      { name: 'PPCNo', label: 'PPC No.', type: 'text' },
      { name: 'LotId', label: 'Lot ID', type: 'text' },
      { name: 'LotSerialNo', label: 'Lot Serial No.', type: 'text' },
      { name: 'LotQRCodeNo', label: 'Lot QR Code No.', type: 'text' },
      { name: 'LotQRCodeLabel', label: 'Lot QR Code Label', type: 'text' },
      { name: 'LotQRCodeImage', label: 'Lot QR Code Image (path/URL)', type: 'text' },
      { name: 'MilkosensCurrentLotMaxSize', label: 'Current Lot Max Size', type: 'number' },
    ],
  },

  milkosensQrMaster: {
    key: 'milkosens-qr-master',
    title: 'Milkosens QR Code Master',
    subtitle: 'Algorithm 3 — visible to Production Department, Admin, or R&D only.',
    endpoint: '/milkosens-qr-master',
    pk: 'id',
    pkEditable: false,
    fields: [
      { name: 'PPCNo', label: 'PPC No.', type: 'text' },
      { name: 'NoOfProductsNeedNewQRCode', label: 'Products Needing New QR Code', type: 'number' },
      { name: 'ProductName', label: 'Product Name', type: 'text', default: 'Milkosens' },
      { name: 'MilkosensSerialNo', label: 'Milkosens Serial No.', type: 'text' },
      { name: 'MilkosensQRCode', label: 'Milkosens QR Code (image/path)', type: 'text' },
      { name: 'MilkosensQRCodeLabel', label: 'Milkosens QR Code Label', type: 'text' },
      { name: 'MilkosensQRCodeNumber', label: 'Milkosens QR Code Number', type: 'text' },
      { name: 'MilkosensLotSerialNo', label: 'Milkosens Lot Serial No.', type: 'text' },
      { name: 'MilkosensCurrentLotSizeFilled', label: 'Current Lot Size Filled', type: 'number' },
      { name: 'StatusOfMilkosens', label: 'Status of Milkosens', type: 'select', options: ['SendToQA', 'InProduction'] },
      { name: 'TotalProductsProducedTillDate', label: 'Total Products Produced Till Date', type: 'number' },
      { name: 'TotalProductsProducedWithQRTillDate', label: 'Total Products Produced (QR generated) Till Date', type: 'number' },
      { name: 'NoProductsNeedNewQRCode', label: 'Products Needing New QR Code', type: 'number' },
      { name: 'MilkosensDispatchFlag', label: 'Dispatch Flag (0/1)', type: 'select', options: YES_NO },
    ],
  },

  milkosensComponentMapping: {
    key: 'milkosens-component-mapping',
    title: 'Milkosens ↔ Component QR Mapping',
    subtitle: 'Algorithm 4 — map Milkosens serial to component QR codes (PCB, Motor, Sensor, Display, Adapter, Controller).',
    endpoint: '/milkosens-component-mapping',
    pk: 'id',
    pkEditable: false,
    fields: [
      { name: 'LotId', label: 'Lot ID', type: 'text' },
      { name: 'MilkosensQRCodeNo', label: 'Milkosens QR Code No.', type: 'text' },
      { name: 'MilkosensQRCodeLabel', label: 'Milkosens QR Code Label', type: 'text' },
      { name: 'MilkosensQRCodeImage', label: 'Milkosens QR Code Image (path/URL)', type: 'text' },
      { name: 'MilkosensSerialNo', label: 'Milkosens Serial No.', type: 'number' },
      { name: 'QRCodePCB', label: 'QR Code — PCB', type: 'text' },
      { name: 'QRCodeMotor', label: 'QR Code — Motor', type: 'text' },
      { name: 'QRCodeSensor', label: 'QR Code — Sensor', type: 'text' },
      { name: 'QRCodeDisplay', label: 'QR Code — Display', type: 'text' },
      { name: 'QRCodeAdapter', label: 'QR Code — Adapter', type: 'text' },
      { name: 'QRCodeController', label: 'QR Code — Controller', type: 'text' },
    ],
  },

  milkosensFaultMaster: {
    key: 'milkosens-fault-master',
    title: 'Milkosens Fault Master',
    subtitle: 'Algorithm 5 — visible to QA Department, Admin, or R&D only.',
    endpoint: '/milkosens-fault-master',
    pk: 'id',
    pkEditable: false,
    fields: [
      { name: 'ProductName', label: 'Product Name', type: 'text', default: 'Milkosens' },
      { name: 'FaultMajorCategoryID', label: 'Fault Major Category ID', type: 'text' },
      { name: 'FaultMajorCategoryName', label: 'Fault Major Category Name', type: 'text', required: true },
      { name: 'FaultMinorCategoryID', label: 'Fault Minor Category ID', type: 'text' },
      { name: 'FaultMinorCategoryName', label: 'Fault Minor Category Name', type: 'text', required: true },
    ],
  },

  communicationLogMilkosens: {
    key: 'communication-log-milkosens',
    title: 'Communication Log — Milkosens',
    subtitle: 'Department hand-off audit trail with current status/operation tracking.',
    endpoint: '/communication-log-milkosens',
    pk: 'id',
    pkEditable: false,
    readOnly: true,
    fields: [
      { name: 'PPCNo', label: 'PPC No.', type: 'text' },
      { name: 'MilkosensSerialNo', label: 'Milkosens Serial No.', type: 'text' },
      { name: 'MilkosensLotNo', label: 'Milkosens Lot No.', type: 'text' },
      { name: 'FromDepartmentName', label: 'From Department', type: 'text' },
      { name: 'ToDepartmentName', label: 'To Department', type: 'text' },
      { name: 'StatusofMilkosens', label: 'Status of Milkosens', type: 'text' },
      { name: 'MilkosensCurrentDepartmentFlag', label: 'Current Department Flag', type: 'text' },
      { name: 'DateTimeOfTransfer', label: 'Date/Time of Transfer', type: 'text' },
    ],
  },
};

/*export const navGroups = [
  {
    title: 'Web User Management',
    items: ['userGroups', 'customers', 'locations', 'maxUserCount', 'webUsers', 'mobileUsers'],
  },
  {
    title: 'PCB QA Test Process',
    items: ['ppcLotComponent', 'componentLotMaster', 'componentQrMaster', 'componentFaultMaster', 'communicationLogComponent'],
    processLink: { path: '/process/component-test', label: 'Component Test Process' },
  },
  {
    title: 'Milkosens QA Test Process',
    items: ['ppcMilkosens', 'milkosensLotMaster', 'milkosensQrMaster', 'milkosensComponentMapping', 'milkosensFaultMaster', 'communicationLogMilkosens'],
    processLink: { path: '/process/milkosens-test', label: 'Milkosens Test Process' },
  },
];
*/
export const navGroups = [
  {
    title: 'Web User Management',
    items: ['userGroups', 'customers', 'locations', 'maxUserCount', 'webUsers', 'mobileUsers'],
  },
  {
    title: 'PCB QA Test Process',
    items: ['ppcLotComponent', 'componentLotMaster', 'componentQrMaster', 'componentFaultMaster', 'communicationLogComponent'],
    processLinks: [
      { path: '/process/component-test', label: 'Component Test Process' },
      { path: '/process/ppc-lot-qr-code', label: 'PPC Lot New QR Code' },
    ],
  },
  {
    title: 'Milkosens QA Test Process',
    items: ['ppcMilkosens', 'milkosensLotMaster', 'milkosensQrMaster', 'milkosensComponentMapping', 'milkosensFaultMaster', 'communicationLogMilkosens'],
    processLinks: [
      { path: '/process/milkosens-test', label: 'Milkosens Test Process' },
    ],
  },
];