import React from 'react';

/**
 * Each entity config drives a generic CRUD page:
 *  - key: route slug
 *  - title: page heading
 *  - endpoint: backend REST path (mounted under /api)
 *  - pk: primary key field name
 *  - pkEditable: whether the pk can be typed by the user on create (true for
 *    business keys like CustomerID, false for auto-increment ids)
 *  - fields: form + table field definitions
 */

const YES_NO = [
  { value: 1, label: 'Active (1)' },
  { value: 0, label: 'Inactive (0)' },
];

export const entities = {
  userGroups: {
    key: 'user-groups',
    title: 'Web Group Name Master',
    subtitle: 'Create user groups under a Group Type (Internal User / Field User) for the web application.',
    endpoint: '/user-groups',
    pk: 'GroupNameID',
    pkEditable: true,
    fields: [
      { name: 'GroupNameID', label: 'Group Name ID', type: 'text', required: true },
      { name: 'UserGroupType', label: 'User Group Type', type: 'select', options: ['Internal User', 'Field User'], required: true },
      { name: 'UserGroupName', label: 'User Group Name', type: 'text', placeholder: 'R&D / Admin / Customer' },
      { name: 'GroupNameDescription', label: 'Description', type: 'textarea' },
    ],
  },

  customers: {
    key: 'customers',
    title: 'Web Customer Master',
    subtitle: 'Visible only to the REILADMIN user.',
    endpoint: '/customers',
    pk: 'CustomerID',
    pkEditable: true,
    fields: [
      { name: 'CustomerID', label: 'Customer ID', type: 'text', required: true },
      { name: 'CustomerName', label: 'Customer Name', type: 'text', required: true },
      {
        name: 'GroupNameID',
        label: 'Group Name',
        type: 'select',
        optionsEndpoint: '/user-groups',
        optionsValue: 'GroupNameID',
        optionsLabel: 'UserGroupName',
      },
      { name: 'CustomerDescription', label: 'Customer Description', type: 'textarea' },
    ],
  },

  locations: {
    key: 'locations',
    title: 'Web Location Master',
    subtitle: 'Visible to (CustomerName+ADMIN), REILADMIN, and REILMarketingADMIN users.',
    endpoint: '/locations',
    pk: 'LocationID',
    pkEditable: true,
    fields: [
      { name: 'LocationID', label: 'Location ID', type: 'text', required: true },
      {
        name: 'GroupNameID',
        label: 'Group Name',
        type: 'select',
        optionsEndpoint: '/user-groups',
        optionsValue: 'GroupNameID',
        optionsLabel: 'UserGroupName',
        uiOnly: true,
      },
      {
        name: 'CustomerID',
        label: 'Customer',
        type: 'select',
        optionsEndpoint: '/customers',
        optionsValue: 'CustomerID',
        optionsLabel: 'CustomerName',
        dependsOn: 'GroupNameID',
        filterKey: 'GroupNameID',
        required: true,
      },
      { name: 'LocationName', label: 'Location Name', type: 'text', required: true },
      { name: 'LocationDescription', label: 'Location Description', type: 'textarea' },
    ],
  },

  maxUserCount: {
    key: 'max-user-count',
    title: 'Maximum Field User Count',
    subtitle: 'Per-customer user limits. Note: no max user limit applies where Group Type = Internal.',
    endpoint: '/max-user-count',
    pk: 'CustomerID',
    pkEditable: true,
    fields: [
      {
        name: 'GroupNameID',
        label: 'Group Name',
        type: 'select',
        optionsEndpoint: '/user-groups',
        optionsValue: 'GroupNameID',
        optionsLabel: 'UserGroupName',
        uiOnly: true,
      },
      {
        name: 'CustomerID',
        label: 'Customer',
        type: 'select',
        optionsEndpoint: '/customers',
        optionsValue: 'CustomerID',
        optionsLabel: 'CustomerName',
        dependsOn: 'GroupNameID',
        filterKey: 'GroupNameID',
        required: true,
      },
      { name: 'MaxWebLocationUsers', label: 'Max Web Location Users', type: 'number' },
      { name: 'MaxWebCustomerUsers', label: 'Max Web Customer Users', type: 'number' },
      { name: 'MaxWebMobileAppUsers', label: 'Max Web Mobile App Users', type: 'number' },
      { name: 'MaxMobileUsers', label: 'Max Mobile Users', type: 'number' },
    ],
  },

  webUsers: {
    key: 'web-users',
    title: 'Web User Master',
    subtitle: 'New user creation under a specific User Group (Customer / Location).',
    endpoint: '/web-users',
    pk: 'UserID',
    pkEditable: true,
    fields: [
      { name: 'UserID', label: 'User ID', type: 'text', required: true },
      {
        name: 'GroupNameID',
        label: 'Group Name',
        type: 'select',
        optionsEndpoint: '/user-groups',
        optionsValue: 'GroupNameID',
        optionsLabel: 'UserGroupName',
        uiOnly: true,
        autofill: { UserGroupType: 'UserGroupType', UserGroupName: 'UserGroupName' },
      },
      {
        name: 'CustomerID',
        label: 'Customer',
        type: 'select',
        optionsEndpoint: '/customers',
        optionsValue: 'CustomerID',
        optionsLabel: 'CustomerName',
        dependsOn: 'GroupNameID',
        filterKey: 'GroupNameID',
        autofill: { CustomerName: 'CustomerName' },
      },
      {
        name: 'LocationID',
        label: 'Location',
        type: 'select',
        optionsEndpoint: '/locations',
        optionsValue: 'LocationID',
        optionsLabel: 'LocationName',
        dependsOn: 'CustomerID',
        filterKey: 'CustomerID',
        autofill: { LocationName: 'LocationName' },
      },
      { name: 'UserLevel', label: 'User Level', type: 'select', options: ['ADMIN', 'OFFICER', 'TECHNICIAN', 'Customer', 'Location', 'MobileApp'] },
      { name: 'UserGroupType', label: 'User Group Type', type: 'text', hiddenInForm: true },
      { name: 'UserGroupName', label: 'User Group Name', type: 'text', hiddenInForm: true },
      { name: 'NameOfUser', label: 'Name of User', type: 'text', required: true },
      { name: 'LoginID', label: 'Login ID', type: 'text', required: true },
      { name: 'Password', label: 'Password', type: 'password', required: true },
      { name: 'UserActivationFlag', label: 'Activation Flag', type: 'select', options: YES_NO },
      { name: 'Designation', label: 'Designation', type: 'text' },
      { name: 'EmailID', label: 'Email ID', type: 'text' },
      { name: 'MobileNo', label: 'Mobile No. (10 digits)', type: 'text', maxLength: 10 },
      { name: 'CustomerName', label: 'Customer Name', type: 'text', hiddenInForm: true },
      { name: 'LocationName', label: 'Location Name', type: 'text', hiddenInForm: true },
    ],
  },

  mobileUsers: {
    key: 'mobile-users',
    title: 'Mobile User Master',
    subtitle: 'Mobile app user creation under Customer / Location.',
    endpoint: '/mobile-users',
    pk: 'MobileAppUserID',
    pkEditable: true,
    fields: [
      { name: 'MobileAppUserID', label: 'Mobile App User ID', type: 'text', required: true },
      {
        name: 'GroupNameID',
        label: 'Group Name',
        type: 'select',
        optionsEndpoint: '/user-groups',
        optionsValue: 'GroupNameID',
        optionsLabel: 'UserGroupName',
        uiOnly: true,
        autofill: { UserGroupType: 'UserGroupType', UserGroupName: 'UserGroupName' },
      },
      {
        name: 'CustomerID',
        label: 'Customer',
        type: 'select',
        optionsEndpoint: '/customers',
        optionsValue: 'CustomerID',
        optionsLabel: 'CustomerName',
        dependsOn: 'GroupNameID',
        filterKey: 'GroupNameID',
        autofill: { CustomerName: 'CustomerName' },
      },
      {
        name: 'LocationID',
        label: 'Location',
        type: 'select',
        optionsEndpoint: '/locations',
        optionsValue: 'LocationID',
        optionsLabel: 'LocationName',
        dependsOn: 'CustomerID',
        filterKey: 'CustomerID',
        autofill: { LocationName: 'LocationName' },
      },
      { name: 'UserGroupType', label: 'User Group Type', type: 'text', hiddenInForm: true },
      { name: 'UserGroupName', label: 'User Group Name', type: 'text', hiddenInForm: true },
      { name: 'NameOfUser', label: 'Name of User', type: 'text' },
      { name: 'LoginID', label: 'Login ID', type: 'text' },
      { name: 'Password', label: 'Password', type: 'password' },
      { name: 'UserActivationFlag', label: 'Activation Flag', type: 'select', options: YES_NO },
      { name: 'Designation', label: 'Designation', type: 'text' },
      { name: 'EmailID', label: 'Email ID', type: 'text', required: true, pattern: 'email' },
      { name: 'MobileNo', label: 'Mobile No. (10 digits)', type: 'text', required: true, pattern: 'mobile10', maxLength: 10 },
      { name: 'CustomerName', label: 'Customer Name', type: 'text', hiddenInForm: true },
      { name: 'LocationName', label: 'Location Name', type: 'text', hiddenInForm: true },
    ],
  },

  ppcLotComponent: {
    key: 'ppc-lot-component',
    title: 'PPC Lot Details of Component (PCB)',
    subtitle: 'Algorithm 1 — Part No. and total component count auto-fill from PPC Master.',
    endpoint: '/ppc-lot-component',
    pk: 'id',
    pkEditable: false,
    fields: [
      { name: 'ComponentName', label: 'Component Name', type: 'text', default: 'PCB' },
      { name: 'PPCNo', label: 'PPC No.', type: 'text', required: true },
      { name: 'PartNo', label: 'Part No.', type: 'text' },
      { name: 'TotalComponentsAsPerPPC', label: 'Total Components as per PPC', type: 'number' },
    ],
  },

  componentLotMaster: {
    key: 'component-lot-master',
    title: 'Component Lot Master',
    subtitle: 'Algorithm 2 — map an available (unallotted) QR code to a Lot.',
    endpoint: '/component-lot-master',
    pk: 'id',
    pkEditable: false,
    fields: [
      { name: 'ComponentName', label: 'Component Name', type: 'text', default: 'PCB' },
      {
        name: 'PPCNo',
        label: 'PPC No.',
        type: 'select',
        optionsEndpoint: '/ppc-lot-component',
        optionsValue: 'PPCNo',
        optionsLabel: 'PPCNo',
      },
      { name: 'ComponentLotSerialNo', label: 'Component Lot Serial No.', type: 'text' },
      {
        name: 'ComponentLotQRCodeNo',
        label: 'Component Lot QR Code No.',
        type: 'select',
        optionsEndpoint: '/process/ppc-lot-qr/available?componentName=PCB',
        optionsValue: 'LotQRCodeNo',
        optionsLabel: 'LotQRCodeNo',
        linkGroup: 'qrLink',
        resolveColumn: 'LotQRCodeNo',
      },
      {
        name: 'ComponentLotQRCodeLabel',
        label: 'Component Lot QR Code Label',
        type: 'select',
        optionsEndpoint: '/process/ppc-lot-qr/available?componentName=PCB',
        optionsValue: 'LotQRCodeLabel',
        optionsLabel: 'LotQRCodeLabel',
        linkGroup: 'qrLink',
        resolveColumn: 'LotQRCodeLabel',
      },
      {
        name: 'ComponentLotQRCodeImage',
        label: 'Component Lot QR Code Image (path/URL)',
        type: 'select',
        optionsEndpoint: '/process/ppc-lot-qr/available?componentName=PCB',
        optionsValue: 'LotQRCodeLabel',
        optionsLabel: 'LotQRCodeLabel',
        linkGroup: 'qrLink',
        resolveColumn: 'LotQRCodeImage',
      },
      { name: 'ComponentCurrentLotMaxSize', label: 'Current Lot Max Size', type: 'number' },
    ],
  },

  componentQrMaster: {
    key: 'component-qr-master',
    title: 'Component QR Code Master',
    subtitle: 'Algorithm 3 — generate/print QR codes for components and map to Component Serial No.',
    endpoint: '/component-qr-master',
    pk: 'id',
    pkEditable: false,
    fields: [
      { name: 'ComponentName', label: 'Component Name', type: 'text', default: 'PCB' },
      {
        name: 'PPCNo',
        label: 'PPC No.',
        type: 'select',
        optionsEndpoint: '/ppc-lot-component',
        optionsValue: 'PPCNo',
        optionsLabel: 'PPCNo',
      },
      {
        name: 'ComponentLotQRCodeNo',
        label: 'Component Lot QR Code No.',
        type: 'select',
        optionsEndpoint: '/process/ppc-lot-qr/allotted',
        optionsValue: 'LotQRCodeNo',
        optionsLabel: 'LotQRCodeNo',
        dependsOn: 'PPCNo',
        filterKey: 'PPCNo',
        linkGroup: 'lotLink',
        uiOnly: true,
        render: (row) => row.ComponentLotQRCodeNo || '-',
      },
      {
        name: 'ComponentLotSerialNo',
        label: 'Component Lot Serial No.',
        type: 'select',
        optionsEndpoint: '/process/ppc-lot-qr/allotted',
        optionsValue: 'LotQRCodeNo',
        optionsLabel: 'ComponentLotSerialNo',
        dependsOn: 'PPCNo',
        filterKey: 'PPCNo',
        linkGroup: 'lotLink',
        uiOnly: true,
        render: (row) => row.ComponentLotSerialNo || '-',
      },
      {
        name: 'ComponentLotId',
        label: 'Component Lot ID',
        type: 'select',
        optionsEndpoint: '/process/ppc-lot-qr/allotted',
        optionsValue: 'LotQRCodeNo',
        optionsLabel: 'LotQRCodeNo',
        linkGroup: 'lotLink',
        resolveColumn: 'id',
        hiddenInForm: true,
      },
      { name: 'ComponentSerialNo', label: 'Component Serial No.', type: 'text' },
      {
        name: 'ComponentQRCodeNo',
        label: 'Component QR Code No.',
        type: 'select',
        optionsEndpoint: '/process/ppc-lot-qr/available?componentName=PCB',
        optionsValue: 'LotQRCodeNo',
        optionsLabel: 'LotQRCodeNo',
        linkGroup: 'compQrLink',
        resolveColumn: 'LotQRCodeNo',
      },
      {
        name: 'ComponentQRCodeLabel',
        label: 'Component QR Code Label',
        type: 'select',
        optionsEndpoint: '/process/ppc-lot-qr/available?componentName=PCB',
        optionsValue: 'LotQRCodeLabel',
        optionsLabel: 'LotQRCodeLabel',
        linkGroup: 'compQrLink',
        resolveColumn: 'LotQRCodeLabel',
      },
      {
        name: 'ComponentQRCodeImage',
        label: 'Component QR Code Image (path/URL)',
        type: 'select',
        optionsEndpoint: '/process/ppc-lot-qr/available?componentName=PCB',
        optionsValue: 'LotQRCodeLabel',
        optionsLabel: 'LotQRCodeLabel',
        linkGroup: 'compQrLink',
        resolveColumn: 'LotQRCodeImage',
        render: (row) => {
          if (!row.ComponentQRCodeImage) return '-';
          if (row.ComponentQRCodeImage.startsWith('data:image')) {
            return React.createElement('img', {
              src: row.ComponentQRCodeImage,
              alt: 'QR Code',
              style: { width: '40px', height: '40px', objectFit: 'contain' },
            });
          }
          return row.ComponentQRCodeImage;
        },
      },
      {
        name: 'ComponentDepartmentFlag',
        label: 'Department Flag',
        type: 'select',
        options: [
          { value: 1, label: '1 - Production' },
          { value: 2, label: '2 - QA' },
          { value: 3, label: '3 - FGS' },
        ],
        default: 2,
      },
      {
        name: 'ComponentCurrentLotSizeFilled',
        label: 'Current Lot Size Filled',
        type: 'number',
        hiddenInForm: true,
        default: 0,
      },
      { name: 'ComponentDispatchFlag', label: 'Dispatch Flag (0/1)', type: 'select', options: YES_NO, default: 0 },
      {
        name: 'NoOfNewQRCodeRequired',
        label: 'No. of New QR Code Required',
        type: 'number',
        hiddenInForm: true,
        default: 0,
      },
      {
        name: 'TotalComponentsProducedTillDate',
        label: 'Total Components Produced Till Date',
        type: 'number',
        hiddenInForm: true,
        default: 0,
      },
      {
        name: 'TotalComponentsProducedWithQRTillDate',
        label: 'Total Components Produced (QR generated) Till Date',
        type: 'number',
        hiddenInForm: true,
        default: 0,
      },
      {
        name: 'NoComponentsNeedNewQRCode',
        label: 'Components Needing New QR Code',
        type: 'number',
        hiddenInForm: true,
        default: 0,
      },
    ],
  },

  componentMajorFaultMaster: {
    key: 'component-major-fault-master',
    title: 'Major Fault Category Master (PCB)',
    subtitle: 'Algorithm 4 — Major fault categories for PCB.',
    endpoint: '/component-major-fault-master',
    pk: 'id',
    pkEditable: false,
    fields: [
      { name: 'ComponentName', label: 'Component Name', type: 'text', default: 'PCB' },
      { name: 'FaultMajorCategoryID', label: 'Fault Major Category ID', type: 'text', required: true },
      { name: 'FaultMajorCategoryName', label: 'Fault Major Category Name', type: 'text', required: true },
    ],
  },

  componentMinorFaultMaster: {
    key: 'component-minor-fault-master',
    title: 'Minor Fault Category Master (PCB)',
    subtitle: 'Algorithm 4 — Minor fault categories for PCB, each tied to a Major fault category.',
    endpoint: '/component-minor-fault-master',
    pk: 'id',
    pkEditable: false,
    fields: [
      { name: 'ComponentName', label: 'Component Name', type: 'text', default: 'PCB' },
      {
        name: 'FaultMajorCategoryID',
        label: 'Fault Major Category ID',
        type: 'select',
        optionsEndpoint: '/component-major-fault-master',
        optionsValue: 'FaultMajorCategoryID',
        optionsLabel: 'FaultMajorCategoryID',
        linkGroup: 'majorFaultLink',
        required: true,
      },
      {
        name: 'FaultMajorCategoryName',
        label: 'Fault Major Category Name',
        type: 'select',
        optionsEndpoint: '/component-major-fault-master',
        optionsValue: 'FaultMajorCategoryName',
        optionsLabel: 'FaultMajorCategoryName',
        linkGroup: 'majorFaultLink',
        required: true,
      },
      { name: 'FaultMinorCategoryID', label: 'Fault Minor Category ID', type: 'text', required: true },
      { name: 'FaultMinorCategoryName', label: 'Fault Minor Category Name', type: 'text', required: true },
    ],
  },

  communicationLogComponent: {
    key: 'communication-log-component',
    title: 'Communication Log — Component (PCB)',
    subtitle: 'Department hand-off audit trail for PCB components.',
    endpoint: '/communication-log-component',
    pk: 'id',
    pkEditable: false,
    readOnly: true,
    fields: [
      { name: 'PPCNo', label: 'PPC No.', type: 'text' },
      { name: 'ComponentSerialNo', label: 'Component Serial No.', type: 'text' },
      { name: 'LotNo', label: 'Lot No.', type: 'text' },
      { name: 'FromDepartmentName', label: 'From Department', type: 'text' },
      { name: 'ToDepartmentName', label: 'To Department', type: 'text' },
      { name: 'UserIDFromDept', label: 'User ID (From Dept)', type: 'text' },
      { name: 'OperationNameCompletedByFromDept', label: 'Operation Completed', type: 'text' },
      { name: 'DateTimeOfTransfer', label: 'Date/Time of Transfer', type: 'text' },
    ],
  },

  ppcMilkosens: {
    key: 'ppc-milkosens',
    title: 'MilkoSens Lot Details of Component',
    subtitle: 'Algorithm 1 — Part No. and total product count for a PPC No. Visible to PPC Department, Admin, or R&D only.',
    endpoint: '/ppc-milkosens',
    pk: 'id',
    pkEditable: false,
    fields: [
      { name: 'PPCNo', label: 'PPC No.', type: 'text', required: true },
      { name: 'ProductName', label: 'Product Name', type: 'text', default: 'Milkosens' },
      { name: 'PartNo', label: 'Part No.', type: 'text' },
      { name: 'TotalProductsAsPerPPC', label: 'Total Products as per PPC', type: 'number' },
      { name: 'MaxLotSize', label: 'Max Lot Size', type: 'number' },
    ],
  },

  milkosensLotMaster: {
    key: 'milkosens-lot-master',
    title: 'MilkoSens Lot Master',
    subtitle: 'Algorithm 2 — map an available (unallotted) QR code to a Milkosens Lot. Visible to Production Department, Admin, or R&D only.',
    endpoint: '/milkosens-lot-master',
    pk: 'id',
    pkEditable: false,
    fields: [
      { name: 'ProductName', label: 'Product Name', type: 'text', default: 'Milkosens' },
      {
        name: 'PPCNo',
        label: 'PPC No.',
        type: 'select',
        optionsEndpoint: '/ppc-milkosens',
        optionsValue: 'PPCNo',
        optionsLabel: 'PPCNo',
      },
      { name: 'LotId', label: 'Lot ID', type: 'text' },
      { name: 'LotSerialNo', label: 'Lot Serial No.', type: 'text' },
      {
        name: 'LotQRCodeNo',
        label: 'Lot QR Code No.',
        type: 'select',
        optionsEndpoint: '/process/ppc-lot-qr/available?componentName=Milkosens',
        optionsValue: 'LotQRCodeNo',
        optionsLabel: 'LotQRCodeNo',
        linkGroup: 'milkLotQrLink',
        resolveColumn: 'LotQRCodeNo',
      },
      {
        name: 'LotQRCodeLabel',
        label: 'Lot QR Code Label',
        type: 'select',
        optionsEndpoint: '/process/ppc-lot-qr/available?componentName=Milkosens',
        optionsValue: 'LotQRCodeLabel',
        optionsLabel: 'LotQRCodeLabel',
        linkGroup: 'milkLotQrLink',
        resolveColumn: 'LotQRCodeLabel',
      },
      {
        name: 'LotQRCodeImage',
        label: 'Lot QR Code Image (path/URL)',
        type: 'select',
        optionsEndpoint: '/process/ppc-lot-qr/available?componentName=Milkosens',
        optionsValue: 'LotQRCodeLabel',
        optionsLabel: 'LotQRCodeLabel',
        linkGroup: 'milkLotQrLink',
        resolveColumn: 'LotQRCodeImage',
      },
      { name: 'MilkosensCurrentLotMaxSize', label: 'Current Lot Max Size', type: 'number' },
    ],
  },

  milkosensQrMaster: {
    key: 'milkosens-qr-master',
    title: 'MilkoSens QR Code Master',
    subtitle: 'Algorithm 3 — generate/print QR codes for Milkosens units and map to Milkosens Serial No. Visible to Production Department, Admin, or R&D only.',
    endpoint: '/milkosens-qr-master',
    pk: 'id',
    pkEditable: false,
    fields: [
      { name: 'ProductName', label: 'Product Name', type: 'text', default: 'Milkosens' },
      {
        name: 'PPCNo',
        label: 'PPC No.',
        type: 'select',
        optionsEndpoint: '/ppc-milkosens',
        optionsValue: 'PPCNo',
        optionsLabel: 'PPCNo',
      },
      {
        name: 'MilkosensLotSerialNo',
        label: 'Milkosens Lot Serial No.',
        type: 'select',
        optionsEndpoint: '/milkosens-lot-master',
        optionsValue: 'LotSerialNo',
        optionsLabel: 'LotSerialNo',
        dependsOn: 'PPCNo',
        filterKey: 'PPCNo',
      },
      { name: 'MilkosensSerialNo', label: 'Milkosens Serial No.', type: 'text' },
      {
        name: 'MilkosensQRCodeNumber',
        label: 'Milkosens QR Code Number',
        type: 'select',
        optionsEndpoint: '/process/ppc-lot-qr/available?componentName=Milkosens',
        optionsValue: 'LotQRCodeNo',
        optionsLabel: 'LotQRCodeNo',
        linkGroup: 'milkQrLink',
        resolveColumn: 'LotQRCodeNo',
      },
      {
        name: 'MilkosensQRCodeLabel',
        label: 'Milkosens QR Code Label',
        type: 'select',
        optionsEndpoint: '/process/ppc-lot-qr/available?componentName=Milkosens',
        optionsValue: 'LotQRCodeLabel',
        optionsLabel: 'LotQRCodeLabel',
        linkGroup: 'milkQrLink',
        resolveColumn: 'LotQRCodeLabel',
      },
      {
        name: 'MilkosensQRCode',
        label: 'Milkosens QR Code (image/path)',
        type: 'select',
        optionsEndpoint: '/process/ppc-lot-qr/available?componentName=Milkosens',
        optionsValue: 'LotQRCodeLabel',
        optionsLabel: 'LotQRCodeLabel',
        linkGroup: 'milkQrLink',
        resolveColumn: 'LotQRCodeImage',
        render: (row) => {
          if (!row.MilkosensQRCode) return '-';
          if (row.MilkosensQRCode.startsWith('data:image')) {
            return React.createElement('img', {
              src: row.MilkosensQRCode,
              alt: 'QR Code',
              style: { width: '40px', height: '40px', objectFit: 'contain' },
            });
          }
          return row.MilkosensQRCode;
        },
      },
      { name: 'StatusOfMilkosens', label: 'Status of Milkosens', type: 'select', options: ['InProduction', 'SendToQA'], default: 'InProduction' },
      {
        name: 'MilkosensCurrentLotSizeFilled',
        label: 'Current Lot Size Filled',
        type: 'number',
        hiddenInForm: true,
        default: 0,
      },
      { name: 'MilkosensDispatchFlag', label: 'Dispatch Flag (0/1)', type: 'select', options: YES_NO, default: 0 },
      {
        name: 'TotalProductsProducedTillDate',
        label: 'Total Products Produced Till Date',
        type: 'number',
        hiddenInForm: true,
        default: 0,
      },
      {
        name: 'TotalProductsProducedWithQRTillDate',
        label: 'Total Products Produced (QR generated) Till Date',
        type: 'number',
        hiddenInForm: true,
        default: 0,
      },
      {
        name: 'NoProductsNeedNewQRCode',
        label: 'Products Needing New QR Code',
        type: 'number',
        hiddenInForm: true,
        default: 0,
      },
    ],
  },

  milkosensComponentMapping: {
    key: 'milkosens-component-mapping',
    title: 'Milkosens ↔ Component QR Mapping',
    subtitle: 'Algorithm 4 — map Milkosens serial to component QR codes (PCB, Motor, Sensor, Display, Adapter, Controller).',
    endpoint: '/milkosens-component-mapping',
    pk: 'id',
    pkEditable: false,
    fields: [
      {
        name: 'LotId',
        label: 'Lot ID',
        type: 'select',
        optionsEndpoint: '/milkosens-lot-master',
        optionsValue: 'LotId',
        optionsLabel: 'LotId',
      },
      {
        name: 'MilkosensQRCodeNo',
        label: 'Milkosens QR Code No.',
        type: 'select',
        optionsEndpoint: '/milkosens-qr-master',
        optionsValue: 'MilkosensQRCodeNumber',
        optionsLabel: 'MilkosensQRCodeNumber',
        linkGroup: 'milkMapLink',
        resolveColumn: 'MilkosensQRCodeNumber',
      },
      {
        name: 'MilkosensQRCodeLabel',
        label: 'Milkosens QR Code Label',
        type: 'select',
        optionsEndpoint: '/milkosens-qr-master',
        optionsValue: 'MilkosensQRCodeLabel',
        optionsLabel: 'MilkosensQRCodeLabel',
        linkGroup: 'milkMapLink',
        resolveColumn: 'MilkosensQRCodeLabel',
      },
      {
        name: 'MilkosensQRCodeImage',
        label: 'Milkosens QR Code Image (path/URL)',
        type: 'select',
        optionsEndpoint: '/milkosens-qr-master',
        optionsValue: 'MilkosensQRCodeLabel',
        optionsLabel: 'MilkosensQRCodeLabel',
        linkGroup: 'milkMapLink',
        resolveColumn: 'MilkosensQRCode',
        render: (row) => {
          if (!row.MilkosensQRCodeImage) return '-';
          if (row.MilkosensQRCodeImage.startsWith('data:image')) {
            return React.createElement('img', {
              src: row.MilkosensQRCodeImage,
              alt: 'QR Code',
              style: { width: '40px', height: '40px', objectFit: 'contain' },
            });
          }
          return row.MilkosensQRCodeImage;
        },
      },
      {
        name: 'MilkosensSerialNo',
        label: 'Milkosens Serial No.',
        type: 'select',
        optionsEndpoint: '/milkosens-qr-master',
        optionsValue: 'MilkosensSerialNo',
        optionsLabel: 'MilkosensSerialNo',
        linkGroup: 'milkMapLink',
        resolveColumn: 'MilkosensSerialNo',
      },
      { name: 'QRCodePCB', label: 'QR Code — PCB', type: 'text', scannable: true },
      { name: 'QRCodeMotor', label: 'QR Code — Motor', type: 'text', scannable: true },
      { name: 'QRCodeSensor', label: 'QR Code — Sensor', type: 'text', scannable: true },
      { name: 'QRCodeDisplay', label: 'QR Code — Display', type: 'text', scannable: true },
      { name: 'QRCodeAdapter', label: 'QR Code — Adapter', type: 'text', scannable: true },
      { name: 'QRCodeController', label: 'QR Code — Controller', type: 'text', scannable: true },
    ],
  },

  milkosensMajorFaultMaster: {
    key: 'milkosens-major-fault-master',
    title: 'MilkoSens Major Fault Category Master',
    subtitle: 'Algorithm 5 — Major fault categories for Milkosens. Visible to QA Department, Admin, or R&D only.',
    endpoint: '/milkosens-major-fault-master',
    pk: 'id',
    pkEditable: false,
    fields: [
      { name: 'ProductName', label: 'Product Name', type: 'text', default: 'Milkosens' },
      { name: 'FaultMajorCategoryID', label: 'Fault Major Category ID', type: 'text', required: true },
      { name: 'FaultMajorCategoryName', label: 'Fault Major Category Name', type: 'text', required: true },
    ],
  },

  milkosensMinorFaultMaster: {
    key: 'milkosens-minor-fault-master',
    title: 'MilkoSens Minor Fault Category Master',
    subtitle: 'Algorithm 5 — Minor fault categories for Milkosens, each tied to a Major fault category. Visible to QA Department, Admin, or R&D only.',
    endpoint: '/milkosens-minor-fault-master',
    pk: 'id',
    pkEditable: false,
    fields: [
      { name: 'ProductName', label: 'Product Name', type: 'text', default: 'Milkosens' },
      {
        name: 'FaultMajorCategoryID',
        label: 'Fault Major Category ID',
        type: 'select',
        optionsEndpoint: '/milkosens-major-fault-master',
        optionsValue: 'FaultMajorCategoryID',
        optionsLabel: 'FaultMajorCategoryID',
        linkGroup: 'milkosensMajorFaultLink',
        required: true,
      },
      {
        name: 'FaultMajorCategoryName',
        label: 'Fault Major Category Name',
        type: 'select',
        optionsEndpoint: '/milkosens-major-fault-master',
        optionsValue: 'FaultMajorCategoryName',
        optionsLabel: 'FaultMajorCategoryName',
        linkGroup: 'milkosensMajorFaultLink',
        required: true,
      },
      { name: 'FaultMinorCategoryID', label: 'Fault Minor Category ID', type: 'text', required: true },
      { name: 'FaultMinorCategoryName', label: 'Fault Minor Category Name', type: 'text', required: true },
    ],
  },

  communicationLogMilkosens: {
    key: 'communication-log-milkosens',
    title: 'Communication Log — Milkosens',
    subtitle: 'Department hand-off audit trail with current status/operation tracking.',
    endpoint: '/communication-log-milkosens',
    pk: 'id',
    pkEditable: false,
    readOnly: true,
    fields: [
      { name: 'PPCNo', label: 'PPC No.', type: 'text' },
      { name: 'MilkosensSerialNo', label: 'Milkosens Serial No.', type: 'text' },
      { name: 'MilkosensLotNo', label: 'Milkosens Lot No.', type: 'text' },
      { name: 'FromDepartmentName', label: 'From Department', type: 'text' },
      { name: 'ToDepartmentName', label: 'To Department', type: 'text' },
      { name: 'StatusofMilkosens', label: 'Status of Milkosens', type: 'text' },
      { name: 'MilkosensCurrentDepartmentFlag', label: 'Current Department Flag', type: 'text' },
      { name: 'DateTimeOfTransfer', label: 'Date/Time of Transfer', type: 'text' },
    ],
  },
};

export const navGroups = [
  {
    title: 'Web User Management',
    items: ['userGroups', 'customers', 'locations', 'maxUserCount', 'webUsers', 'mobileUsers'],
  },
  {
    title: 'PCB QA Test Process',
    items: ['ppcLotComponent', 'componentLotMaster', 'componentQrMaster', 'componentMajorFaultMaster', 'componentMinorFaultMaster', 'communicationLogComponent'],
    processLinks: [
      { path: '/process/component-test', label: 'Component Test Process' },
      { path: '/process/ppc-lot-qr-code', label: 'PPC Lot New QR Code' },
    ],
  },
  {
    title: 'Milkosens QA Test Process',
    items: ['ppcMilkosens', 'milkosensLotMaster', 'milkosensQrMaster', 'milkosensComponentMapping', 'milkosensMajorFaultMaster', 'milkosensMinorFaultMaster', 'communicationLogMilkosens'],
    processLinks: [
      { path: '/process/milkosens-test', label: 'MilkoSens Component Test Process' },
      { path: '/process/milkosens-lot-qr-code', label: 'MilkoSens Lot New QR Code' },
    ],
  },
];